version: "3.8"
services:
  email-connector:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/app/
    command: pwsh /app/app.ps1 # instead of ./script.sh
  # uncomment for chedulet restart
  # watchdog:
  #   image: docker:cli
  #   volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
  #   command:
  #     [
  #       "/bin/sh",
  #       "-c",
  #       "while true; do sleep 86400; docker restart [[REPLACE WITH COTNAINER NAME]]; done"
  #     ]
  #   restart: unless-stopped
